## Compare DataFrame and get all the rows of DataFrame that do not exist in another DataFrame

In [0]:
df1 = spark.createDataFrame(
  [('Shiva', 'Appu'), ('Teja', 'Sweety'), ('Bhavishya', 'Bhavi')],
  ['name','nick_name']
)
df1.show(truncate=False)

+---------+---------+
|name     |nick_name|
+---------+---------+
|Shiva    |Appu     |
|Teja     |Sweety   |
|Bhavishya|Bhavi    |
+---------+---------+

In [0]:
df2 = spark.createDataFrame(
  [('Shiva', 'Chinu'), ('Teja', 'Sweety'), ('Bhavishya', 'Bhavi')],
  ['name','nick_name']
)
df2.show(truncate=False)

+---------+---------+
|name     |nick_name|
+---------+---------+
|Shiva    |Chinu    |
|Teja     |Sweety   |
|Bhavishya|Bhavi    |
+---------+---------+

### Get all rows in df1 that does not exist in df2

In [0]:
df1.exceptAll(df2).show()

+-----+---------+
| name|nick_name|
+-----+---------+
|Shiva|     Appu|
+-----+---------+